- name: Install extra packages
  yum:
    name: "{{ extra_packages }}"

- name: Update my.cnf
  copy:
    src: /home/devops/lab2-files/my.cnf
    dest: "{{ configure_database_path }}"
    owner: mysql
    group: mysql
    mode: 0644
    seuser: system_u
    setype: mysqld_etc_t
    force: yes

- name: Start MariaDB
  service:
    name:  "{{ db_service }}"
    state: started
    enabled: true
